# Site
repository: wonyongg/github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 황원용(WonYong Hwang)
title: 주니어 백엔드 개발자
email: kakaohwy@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  wonyongg
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: wonyongpic
linkedin_username: wonyonghwang
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 티스토리 기술 블로그
  icon: fas fa-globe
  url: https://suzuworld.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/wonyong.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 제 이름은 황원용입니다. 2023년 2월에 코드스테이츠 백엔드 부트캠프를 수료하고 현재 구직 중입니다.

  저는 <mark>JAVA</mark>와 <mark>Spring Framework</mark>을 활용한 웹 애플리케이션 개발을 공부했습니다.

content:
  - title: Skills  # Title for the section
    quote: >
      공부하고 있거나, 공부했던 기술입니다.
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * <strong>Python</strong> : 대학교에서 1년 간 교양 수업을 통해 배웠습니다. 교내 코딩 경시 대회에서 장려상 2번 수상한 경험이 있습니다.
          * <strong>Java</strong> : 부트캠프에서 본격적으로 배웠고 현재 주력으로 사용하고 있는 언어입니다. 부트캠프 메인 프로젝트에서 사용했습니다.
          * <strong>Spring Boot</strong>, <strong>Spring MVC</strong>, <strong>Spring Data JPA</strong>, <strong>Spring Data Redis</strong> : 부트캠프에서 처음 배웠고, 메인 프로젝트에서 사용했습니다.
          * <strong>Gradle</strong>, <strong>IntelliJ</strong>

      - layout: left
        title: DataBase
        description: | # this will include new lines to allow paragraphs
          * <strong>MySQL</strong> : 메인프로젝트에서 사용했습니다.
          * <strong>Redis</strong> : 인메모리 DB를 활용한 JWT 토큰 관리와 캐시 서버 구현에 사용했습니다.

      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          * <strong>Github Actions</strong> : 메인 프로젝트에서 서버 배포 자동화를 위해 공부하고 사용했습니다.
          * <strong>AWS(EC2, S3, RDS, CodeDeploy)</strong> : 메인 프로젝트에서 서버 배포를 위해 공부하고 사용했습니다.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 부트캠프 메인 프로젝트
        icon: fab fa-github
        link: https://github.com/wonyongg/seb41_main_027
        caption: 2023.01 - 2023.02
#         link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: https://github.com/wonyongg/seb41_main_027
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        content: |
          - Java, Spring Boot를 사용하여 서버 개발
          - AWS 상에서 배포 및 DB 관리를 위해 EC2, S3, RDS 사용
          - 배포 자동화를 위해 Github Actions 사용
          - 서버 성능에 대한 시각화를 위해 AOP를 활용한 로깅 적용
          - 보다 구체적인 시각화를 위해 Grafana 사용
          - Redis를 이용하여 캐시 서버 적용
          - 코드 리팩토링을 위해 Sonarqube 사용
        quote: >
          우리가 함께 그려나가는 서울 친환경 지도, 여러분들의 장소를 공유해주세요.
        description: | # this will include new lines to allow paragraphs
         이 프로젝트는 코드스테이츠 백엔드 부트캠프에서 진행한 메인프로젝트입니다. 저희 팀은 환경에 관심있는 사람들이 모여 친환경과 관련있는 웹사이트를 만들고자 했습니다. 저희는 국내에서 친환경 가게나 공방, 리샤이클샵 등에 관심있는 사람은 많지만, 관련 장소는 쉽게 찾을 수 없다는 점에 주목해 서울과 인근 지역에 있는 친환경적인 장소와, 비건 레스토랑을 소개하는 웹사이트를 만들었습니다. 저는 백엔드 팀에서 <strong>기본 기능 구현, JWT를 활용한 로그인/로그아웃 구현, Redis를 활용한 토큰 관리와 캐시 서버 구현</strong>을 담당했습니다.

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
##          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            test

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 코드스테이트 백엔드 부트캠프 41기
        caption: 2022.08 - 2023.02
        sub_title: 자바 스프링 백엔드 부트캠프
        quote: | # this will include new lines to allow paragraphs
          자바와 스프링을 메인으로 웹 애플리케이션을 개발하기 위한 전반적인 내용에 대해 공부했습니다.

      - layout: top-middle
        title: 세종대학교
        caption: 2018.03 - 2023.02
        sub_title: 국제학부 일어일문학과 학사
        quote: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: 일본 요코하마 국립 대학교
        caption: 2019.04 - 2020.02
        sub_title: 1년 방문학생
        quote: | # this will include new lines to allow paragraphs
          방문학생 자격으로 1년간 일본에서 공부했습니다.

  - title: Licenses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 정보처리기사 
      - SQLD
      - ADsP

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
