# Site
repository: wonyongg/github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 황원용(WonYong Hwang)
title: 주니어 백엔드 개발자
email: kakaohwy@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  wonyongg
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: wonyongpic
linkedin_username: wonyonghwang
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 티스토리 기술 블로그
  icon: fas fa-globe
  url: https://suzuworld.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/wonyong.jpg
about_content: | # this will include new lines to allow paragraphs

  안녕하세요. 제 이름은 황원용입니다. 대학에서 <mark>일어일문학</mark>을 전공했습니다. 그런데 제 전공과는 다르게 <strong>수학적인 공부를 더 좋아합니다.</strong> 
  단순한 궁금증에 대학에서 교양 수업으로 일변수 미적분학을 수강하기도 했습니다. 대학 생활을 돌이켜보면 전공 수업보다 교양 수업으로 
  수강했던 이공계열 수업이 더 기억에 남고 재밌게 공부했던 것 같습니다. 그래서인지 자연스레 교양 수업으로 들었던 프로그래밍에 관심을 
  가지게 되었고 <mark>정보처리기사</mark> 자격증을 취득하고 개발자가 되기 위해 <mark>부트캠프</mark>에 참여하게 되었습니다.
  
  저는 <strong>오버 커뮤니케이션을 지향합니다.</strong> 이번 프로젝트에서도 팀원들과 외적으로도 많은 이야기를 나눴습니다. 이는 팀원들 간에 친밀감과
  유대감을 형성하게 했고, 결과적으로 중요 사항에 대해 트러블 없이 빠른 결정을 내리는 등 프로젝트의 원활한 진행에 큰 도움이 되었습니다.
   
  저는 <strong>이타적인 개발자 문화에 동경심을 가지고 있습니다.</strong> 그중 오픈 소스를 만들고 공개하는 일은 정말 멋진 일이라고 생각합니다. 평소에
  <strong>개발자스럽지 못한 반복적인 일을 보면 개선하고 싶은 욕구가 샘솟는</strong> 만큼 저 역시 언젠가 오픈 소스를 만들고 팀과 다른 사람들에게 공유하고 
  싶습니다.  

content:
  - title: Skills  # Title for the section
    quote: >
      공부하고 있거나, 공부했던 기술입니다.
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * <strong>Python</strong> : 대학교에서 1년 간 교양 수업을 통해 배웠습니다. 교내 코딩 경시 대회에서 장려상 2번 수상한 경험이 있습니다.
          * <strong>Java</strong> : 부트캠프에서 본격적으로 배웠고 현재 주력으로 사용하고 있는 언어입니다. 모르는 게 있을 때마다 찾아가며 공부하고 있습니다.
          * <strong>Spring Boot</strong>, <strong>Spring MVC</strong>, <strong>Spring Data JPA</strong> : 부트캠프 내 컨텐츠와 인프런 강의를 통해 학습했습니다. 실무에 필요한 내용 위주로 공부했습니다.
          * <strong>Gradle</strong>, <strong>IntelliJ</strong> 부트캠프 내 모든 컨텐츠와 메인 프로젝트에서 사용했습니다. 빌드 도구는 Gradle 외에 사용 경험이 없으며, IntelliJ 외에 다른 IDE는 VScode 사용을 익히고 있습니다.

      - layout: left
        title: DataBase
        description: | # this will include new lines to allow paragraphs
          * <strong>MySQL</strong> : RDMS에 대해 기본적인 내용을 알고 있습니다. 메인프로젝트에서 사용했습니다.
          * <strong>Redis</strong> : NoSQL, 인메모리 DB, 캐시 서버에 대해 학습 후 사용한 경험이 있습니다. 구체적으로 인메모리 DB를 활용한 JWT 토큰 관리와 캐시 서버 구현에 사용했습니다.

      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          * <strong>AWS</strong> : 메인프로젝트에서 배포를 위해 EC2와 RDS, S3를 사용했습니다. CI/CD에 대해 학습한 후, CodePipeLine을 만들어 AWS CodeBuild CodeDeploy를 통한 배포 실습을 한 경험이 있습니다.
          * <strong>Github Actions</strong> : 메인프로젝트에서 서버 배포 자동화를 위해 공부하고 사용했습니다. Githhub Actions가 AWS S3에 빌드 결과물을 전송하면 S3가 이를 CodeDeploy에게 전달하여 EC2에 배포 및 실행하는 플로우로 진행했습니다.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 부트캠프 메인 프로젝트
        icon: fab fa-github
        link: https://github.com/wonyongg/seb41_main_027
        caption: 2023.01 - 2023.02
#         link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: https://github.com/wonyongg/seb41_main_027
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          우리가 함께 그려나가는 서울 친환경 지도, 여러분들의 장소를 공유해주세요.
        about_content: | # this will include new lines to allow paragraphs
          이 프로젝트는 부트캠프에서 진행한 메인 프로젝트입니다. 저희 팀은 서울과 인근 지역에 있는 친환경적인 장소와, 비건 레스토랑을 소개하는 웹사이트를 만들었습니다.
          
          저희 팀은 이번 메인 프로젝트를 통해서 어렵고 복잡한 기능을 구현하는 것보다 설계부터 배포 후 유지보수까지 이어지는 개발 프로세스의 전반적인 내용을 완벽히 구현
          하는 데에 집중을 했습니다. 개발자에게 있어 가장 중요한 것이 성능 최적화부터 안정적인 서버 운영과 높은 유지보수성까지의 
          

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
##          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            test

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 코드스테이트 백엔드 부트캠프 41기
        caption: 2022.08 - 2023.02
        sub_title: 자바 스프링 백엔드 부트캠프
        quote: | # this will include new lines to allow paragraphs
          자바와 스프링을 메인으로 웹 애플리케이션을 개발하기 위한 전반적인 내용에 대해 공부했습니다.

      - layout: top-middle
        title: 세종대학교
        caption: 2018.03 - 2023.02
        sub_title: 국제학부 일어일문학과 학사
        quote: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: 일본 요코하마 국립 대학교
        caption: 2019.04 - 2020.02
        sub_title: 1년 방문학생
        quote: | # this will include new lines to allow paragraphs
          방문학생 자격으로 1년간 일본에서 공부했습니다.

  - title: Licenses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 정보처리기사 
      - SQLD
      - ADsP

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
